// Configuración compartida de Tailwind para el área de empleados.
// Idéntica a la usada en las páginas públicas de Librería Nexus.
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": { "surface-container-high": "#e6e8ef", "on-background": "#191c21", "outline-variant": "#c5c6cc", "on-tertiary-fixed-variant": "#614000", "outline": "#75777c", "surface-bright": "#f8f9ff", "surface-container-lowest": "#ffffff", "tertiary-container": "#332000", "on-secondary": "#ffffff", "inverse-on-surface": "#eff0f7", "primary": "#050e1c", "primary-container": "#1b2432", "on-secondary-container": "#6f2000", "surface-container-low": "#f2f3fa", "tertiary-fixed": "#ffddb1", "primary-fixed-dim": "#bec7da", "on-primary": "#ffffff", "surface-variant": "#e1e2e9", "secondary-fixed-dim": "#ffb59c", "on-secondary-fixed-variant": "#822801", "on-primary-fixed": "#131c2a", "error": "#ba1a1a", "surface-container-highest": "#e1e2e9", "tertiary-fixed-dim": "#f2be71", "on-secondary-fixed": "#390c00", "inverse-primary": "#bec7da", "primary-fixed": "#dae3f6", "secondary-container": "#fe8357", "surface-container": "#eceef4", "inverse-surface": "#2e3136", "on-surface": "#191c21", "surface": "#f8f9ff", "secondary-fixed": "#ffdbcf", "on-primary-fixed-variant": "#3e4757", "on-error": "#ffffff", "background": "#f8f9ff", "surface-dim": "#d8dae0", "on-error-container": "#93000a", "on-tertiary-fixed": "#291800", "tertiary": "#170c00", "on-primary-container": "#828b9d", "on-tertiary-container": "#b0833c", "on-tertiary": "#ffffff", "secondary": "#a23e18", "on-surface-variant": "#45474c", "surface-tint": "#565f6f", "error-container": "#ffdad6" },
      "borderRadius": { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
      "spacing": { "margin-tablet": "2rem", "gutter-mobile": "1rem", "space-lg": "1.5rem", "margin-mobile": "1.25rem", "margin": "3.5rem", "gutter": "1.5rem", "space-2xl": "4rem", "space-sm": "0.5rem", "space-md": "1rem", "space-xl": "2.5rem", "space-xs": "0.25rem" },
      "fontFamily": { "display-md-mobile": ["Literata"], "label-md": ["Manrope"], "body-lg": ["Manrope"], "display-lg-mobile": ["Literata"], "title-lg": ["Manrope"], "display-lg": ["Literata"], "headline-lg": ["Literata"], "headline-sm": ["Literata"], "title-md": ["Manrope"], "display-md": ["Literata"], "body-md": ["Manrope"], "body-sm": ["Manrope"], "label-sm": ["Manrope"], "headline-lg-mobile": ["Literata"], "headline-md": ["Literata"] },
      "fontSize": { "display-md-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "400" }], "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.03em", "fontWeight": "600" }], "body-lg": ["17px", { "lineHeight": "28px", "fontWeight": "400" }], "display-lg-mobile": ["38px", { "lineHeight": "46px", "letterSpacing": "-0.015em", "fontWeight": "400" }], "title-lg": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "600" }], "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "400" }], "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "500" }], "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }], "title-md": ["16px", { "lineHeight": "24px", "fontWeight": "600" }], "display-md": ["44px", { "lineHeight": "52px", "letterSpacing": "-0.015em", "fontWeight": "400" }], "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }], "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }], "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.06em", "fontWeight": "700" }], "headline-lg-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "500" }], "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "500" }] }
    }
  }
};
